name = "PlutoText"
uuid = "3d70afa0-157d-4850-b732-cc71b7b1d788"
authors = ["pdaman"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
